# Generated by Django 2.1.7 on 2019-02-20 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_line_id', models.CharField(blank=True, max_length=30, null=True)),
                ('serif', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('use_time', models.DateTimeField()),
                ('state', models.CharField(choices=[('SENDED', '送信済み'), ('WAITING', '未送信'), ('DRAFT', '下書き')], max_length=1)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
