# Generated by Django 2.1.7 on 2019-02-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramiel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='state',
            field=models.CharField(choices=[('SENDED', '送信済み'), ('WAITING', '未送信'), ('DRAFT', '下書き')], max_length=7),
        ),
    ]
