# Generated by Django 2.1.7 on 2019-03-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramiel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineuser',
            name='app_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
