# Generated by Django 2.1.7 on 2019-02-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramiel', '0002_auto_20190220_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='LINEUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('line_id', models.CharField(max_length=30)),
            ],
        ),
    ]
