# Generated by Django 2.1.7 on 2019-02-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramiel', '0003_lineuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineuser',
            name='line_id',
            field=models.CharField(max_length=100),
        ),
    ]
