# Generated by Django 2.1.7 on 2019-02-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramiel', '0004_auto_20190220_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineuser',
            name='context_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
